### ISSUE TITLE
PWA Not Working

### ISSUE THREAD

**Issue by Malimbu** [creativetimofficial/argon-dashboard-angular#13]
After install PWA or ng add @angular/pwa, there are error where run command ng build --prod

error produce like bottom in console :
Erroneous area:
1: 100% - $icon-size-xl - 1
^.........^

**Comment by rarestoma** [comment]
Hi @Malimbu,

Thank you for working with our products.

Please go to src/assets/scss/core/icons/_icon.scss and replace the following:

`calc(100% - $icon-size-xl - 1);`
to
`calc(100% - #{$icon-size-xl} - 1);`

`calc(100% - $icon-size-lg - 1);`
to
`calc(100% - #{$icon-size-lg} - 1);`

`calc(100% - $icon-size-sm - 1);`
to
`calc(100% - #{$icon-size-sm} - 1);`

Please let me know if it works.

Thank you,
Rares

**Comment by Malimbu** [comment]
@rarestoma thank you. the bug now its fixed and running fine in my local. before with not i change code we try to remove the argon.scss in angular.json file and add argon.scss to file index.html its work fine to.
