### ISSUE TITLE
Only 2 arguments allowed, but 3 were passed.

### ISSUE THREAD

**Issue by tortuvshin** [creativetimofficial/argon-dashboard-angular#2]
Only 2 arguments allowed, but 3 were passed.
    
```
246 │   @include form-validation-state($state, map-get($data, color), map-get($data, icon));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  node_modules\bootstrap\scss\_forms.scss 246:3  form-validation-state()
  node_modules\bootstrap\scss\_forms.scss 246:3  @import
  stdin 21:9                                     root stylesheet
```

**Comment by chelaruc** [comment]
@tortuvshin thank you for using our product. You need to update the bootstrap version. Best, Ciprian

**Comment by ashkaushik** [comment]
@chelaruc I have updated bootstrap and ng-bootstrap, still, I am facing the same issue. can you please help? 
I am using angular 8 with bootstrap 4.3.1 and ng-bootstrap v 5.*.*

**Comment by chelaruc** [comment]
Check this issue: [https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/316](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/316)

**Comment by murilowlima** [comment]
I had the same issue. Can you please help?

```
ERROR in ./src/assets/scss/argon.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--13-3!./src/assets/scss/argon.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
 ^
      Only 2 arguments allowed, but 3 were passed.
    ╷
246 │   @include form-validation-state($state, map-get($data, color), map-get($data, icon));
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\bootstrap\scss\_forms.scss 246:3  form-validation-state()
  node_modules\bootstrap\scss\_forms.scss 246:3  @import
  stdin 35:9                                     root stylesheet
```

Dependencies:
```
    "dependencies": {
        "@angular/animations": "~8.1.2",
        "@angular/common": "~8.1.2",
        "@angular/compiler": "^8.1.3",
        "@angular/core": "^8.1.3",
        "@angular/forms": "^8.1.3",
        "@angular/platform-browser": "^8.1.3",
        "@angular/platform-browser-dynamic": "^8.1.3",
        "@angular/router": "^8.1.3",
        "@ng-bootstrap/ng-bootstrap": "^5.1.0",
        "bootstrap": "^4.3.1",
        "rxjs": "~6.5.2",
        "tslib": "^1.9.0",
        "zone.js": "~0.9.1"
    },
```

**Comment by ashkaushik** [comment]
no luck, brother

**Comment by Gerardlc** [comment]
> Only 2 arguments allowed, but 3 were passed.
> 
> ```
> 246 │   @include form-validation-state($state, map-get($data, color), map-get($data, icon));
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   node_modules\bootstrap\scss\_forms.scss 246:3  form-validation-state()
>   node_modules\bootstrap\scss\_forms.scss 246:3  @import
>   stdin 21:9                                     root stylesheet
> ```

you only need to downgrade to version 4.2.1 so type:

`npm install bootstrap@4.2.1`

and will be fixed

**Comment by Agusnez** [comment]
Downgrading to 4.2.1 means XSS Vulnerabilities in you app. Just keep in mind that. Like #1 says.

**Comment by ixzy24** [comment]
Had the same issues at with bootstrap 4.3.1, fixed it by adding a third parameter to https://github.com/creativetimofficial/argon-dashboard-angular/blob/9a2ce85edf8c5a020375f09ca2ff66e14e528049/src/assets/scss/core/mixins/_forms.scss#L17 

> @mixin form-validation-state($state, $color) {

to

> @mixin form-validation-state($state, $color, $icon) {

**Comment by bsalazar25** [comment]
thanks, its works
