### ISSUE TITLE
datepicker style is broken

### ISSUE THREAD

**Issue by ostar0816** [creativetimofficial/argon-dashboard-angular#3]
argon-version: 1.0.0
"@ng-bootstrap/ng-bootstrap": "4.0.1",
"bootstrap": "4.1.3",

datepicker style is broken like below:
![image](https://user-images.githubusercontent.com/29836051/60958238-04466700-a2d4-11e9-9fa6-79eeb3646fdf.png)

Tried to upgrade bootstrap into 4.3.1 but same error happens.
Please help!

**Comment by chelaruc** [comment]
@ostar0816 You need to import our styles.

**Comment by ostar0816** [comment]
@chelaruc 
How to import your styles? I just cloned this repository and thought all required styles are automatically imported to this repo.

**Comment by chelaruc** [comment]
Check the angular.json file -> styles and tell me what imports you have there.

**Comment by ostar0816** [comment]
Just same as this repo- https://github.com/creativetimofficial/argon-dashboard-angular/blob/master/angular.json

**Comment by ostar0816** [comment]
@chelaruc 
Need to import external style for plugin components?
The thing is datepicker style works right on your document - https://demos.creative-tim.com/argon-dashboard-angular/#/documentation/datepicker but not on this repo.
For the temporary solution, I inspected the datepicker style from documentation and copied them to style.scss of this project project.

**Comment by chelaruc** [comment]
@ostar0816  add this scss code:
```

ngb-datepicker {
  border-radius: $datepicker-border-radius !important;
  direction: ltr !important;


  &,
  & * {
    outline: none;
  }
  &-rtl {
      direction: rtl;
      &.dropdown-menu {
          left: auto;
      }
      table tr td span {
          float: right;
      }
  }
  top: 0!important;
  left: 0!important;
  padding: $datepicker-dropdown-padding!important;
  @include box-shadow($dropdown-box-shadow);

  .bg-light {
    background: transparent !important;
  }

  &:focus {
    outline: none !important;
  }
  .ngb-dp-header {
    border-bottom: none !important;

    ngb-datepicker-navigation {
      color: $primary;

      .ngb-dp-arrow{
        justify-content: center !important;

        &:hover{
          background: #e9ecef;
          border-radius: .375rem;
        }
      }

      .ngb-dp-arrow-btn {
        margin: 0 !important;
        top: -3px;

        .ngb-dp-navigation-chevron {
          color: $primary;
          width: 6px;
          height: 6px;
        }
      }
      ngb-datepicker-navigation-select {
        .custom-select {
          font-weight: 300;
          color: $primary;
          border: none !important;
          background: transparent !important;
          -webkit-appearance: menulist !important;
          box-shadow: none !important;

          &:hover{
            background: #e9ecef !important;
            border-radius: .375rem;
          }
        }
      }
    }
  }
  .ngb-dp-months {
    ngb-datepicker-month-view {
      .ngb-dp-week {
        border: none;
        .ngb-dp-weekday {
          color: $primary;
          padding-top: 10px;
          opacity: 0.8;
          font-style: normal !important;
          line-height: 20px;
          font-weight: 300;
          width: 36px;
          height: 36px;
          font-size: .875rem;
          transition: all .15s ease;
          text-align: center;
          border: none;
        }
        .small {
          font-size: 14px;
        }
        .ngb-dp-day {
          font-size: .875rem;
          width: 36px;
          height: 36px;
          transition: all .15s ease;
          text-align: center;
          border: none;
          border-radius: 50%;

          .btn-light,
          .custom-day {
            width: 36px;
            height: 36px;
            box-shadow: none;
            color: #525f7f;
            border-radius: 50%;
            align-items: center;
            display: grid;

            &:hover,
            &:active {
              box-shadow: none;
              border: none;
              background-color: transparent;
            }

            &.faded{
              border-radius: 0;
            }
            &.range{
              color: $white;
              &:hover{
                background: #5e72e4;
              }
            }
            &.range-start{
              border-top-right-radius: 0;
              border-bottom-right-radius: 0;
            }
            &.range-end{
              border-top-left-radius: 0;
              border-bottom-left-radius: 0;
            }
          }
          &:hover,
          &:active {
            box-shadow: none;
            border: none;
            background-color: transparent;
          }
          .text-muted {
            color: #adb5bd;
          }
        }
      }
    }
  }
}
.datepicker-container {
  input option {
    display: none;
  }
}

.custom-day.range{
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
  color: #fff;
  background: #5e72e4;
  box-shadow: none;
  font-size: .875rem;
  width: 36px;
  height: 36px;
  transition: all .15s ease;
  text-align: center;
  border: none;
  border-radius: 50%;

  &.faded{
    border-radius: 0;
  }
}

```

I'll update the product tomorrow to fix this.

**Comment by ostar0816** [comment]
I already did that :)
I will look forward to the product update. This is really amazing light-weighted dashboard. I love this!
Thanks a lot

**Comment by bielas** [comment]
@chelaruc can you update also this issue when you update the repo?

**Comment by bielas** [comment]
hey guys, when are you going to fix this?

**Comment by chelaruc** [comment]
Hi, @bielas! Can you download the product again?

**Comment by Robokishan** [comment]
i am still having a problem. steps i used
1 . git clone the repo
2. npm install in directory
3. npm start
4. copy and paste code from the documentation [https://demos.creative-tim.com/argon-dashboard-angular/#/documentation/datepicker](url)
5. but still same as mentioned in first pic of this post

**Comment by rarestoma** [comment]
Hi @Robokishan,

Thank you for working with our products.

This is an issue from our last update, please go to src/assets/scss/angular-differences/plugins/_ng-bootstrap.scss and do the following changes:

1. Add `background: #fff;` to` .ngb-dp-header`.
2. At line 88 change` ngb-datepicker-month-view` to `ngb-datepicker-month`
3. Add `background: #fff;` to `.ngb-dp-week`

Please let me know if it works.

Thank you,
Rares

**Comment by sasithahtl** [comment]
> Hi @Robokishan,
> 
> Thank you for working with our products.
> 
> This is an issue from our last update, please go to src/assets/scss/angular-differences/plugins/_ng-bootstrap.scss and do the following changes:
> 
> 1. Add `background: #fff;` to `.ngb-dp-header`.
> 2. At line 88 change `ngb-datepicker-month-view` to `ngb-datepicker-month`
> 3. Add `background: #fff;` to `.ngb-dp-week`
> 
> Please let me know if it works.
> 
> Thank you,
> Rares

Thank you! this worked.
