### ISSUE TITLE
Sidebar menu with submenu toggle issue

### ISSUE THREAD

**Issue by nikiller291189** [creativetimofficial/argon-dashboard-angular#6]
<ul class="nav navbar-nav">
        <li *ngFor="let menuItem of menuItems" class="{{menuItem.class}} nav-item">
          <a routerLinkActive="active" [routerLink]="[menuItem.path]" class="nav-link">
            <i class="ni {{menuItem.icon}}"></i>
            //something....
          </a>
       
            <ul class="nav">
              <li *ngFor="let submenuItem of menuItem.submenu" class="{{submenuItem.class}} nav-link-inner--text">
                <a routerLinkActive="active" [routerLink]="[submenuItem.path]" class="nav-link">
                  <i class="ni {{submenuItem.icon}}"></i>
                  {{submenuItem.title}}
                </a>
              </li>
            </ul>
        
        </li>
      </ul>

**Comment by chelaruc** [comment]
Hello there, @nikiller291189 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Ciprian
Developer @ [Creative-Tim.com](https://creative-tim.com)
